# This rule is not used by the project learn-operators itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to app.learn-operators.michelegiornetta.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: learn-operators
    app.kubernetes.io/managed-by: kustomize
  name: notification-viewer-role
rules:
- apiGroups:
  - app.learn-operators.michelegiornetta.com
  resources:
  - notifications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.learn-operators.michelegiornetta.com
  resources:
  - notifications/status
  verbs:
  - get
